enum ImageTypeEnum {
  EVENT
  EVENT_SERIES
  TALENT
  VENUE
}

type ImageDetails {
  id: ID!
  imageType: ImageTypeEnum!
  sourceUrl: String!
  mimeType: String!
  width: Int!
  height: Int!
  dominantColor: String!
  ratio: Float!
  resizeVersion: Int!
  modifiedDate: String!
}

type ImageIteration {
  actionId: ID!
  iterationId: ID!
}

type ImageResult {
  image: ImageDetails
}

type Query {
  image(id: ID!): ImageResult
}

input CreateTagInput {
  id: ID!
  type: ImageTypeEnum!
  url: String!
}

type AddImageOutput {
  image: ImageDetails
}

type ReprocessAllImagesOutput {
  iteration: ImageIteration
}

type Mutation {
  addImage(input: CreateTagInput!): AddImageOutput
  reprocessAllImages: ReprocessAllImagesOutput
}
