enum TagTypeEnum {
  MEDIUM
  STYLE
  GEO
  AUDIENCE
}

type TagDetail {
  tagType: TagTypeEnum!
  id: ID!
  label: String!
}

type TagSet {
  medium: [TagDetail!]
  style: [TagDetail!]
  geo: [TagDetail!]
  audience: [TagDetail!]
}

type Query {
  tags: TagSet!
}

input CreateTagInput {
  tagType: TagTypeEnum!
  label: String!
}

type CreateTagOutput {
  tag: TagDetail
}

input DeleteTagInput {
  tagType: TagTypeEnum!
  id: ID!
}

type DeleteTagOutput {
  ok: Boolean
}

type Mutation {
  createTag(input: CreateTagInput!): CreateTagOutput
  deleteTag(input: DeleteTagInput!): DeleteTagOutput
}
