export const NOT_REQUIRED = "NOT_REQUIRED";
export const REQUIRED = "REQUIRED";
export const REQUIRED_FOR_NON_MEMBERS = "REQUIRED_FOR_NON_MEMBERS";

export const ALLOWED_VALUES = [
  NOT_REQUIRED,
  REQUIRED,
  REQUIRED_FOR_NON_MEMBERS
];
