export const THEATRE = "THEATRE";
export const ART_GALLERY = "ART_GALLERY";
export const CONCERT_HALL = "CONCERT_HALL";
export const EXHIBITION_HALL = "EXHIBITION_HALL";
export const PERFORMING_ARTS_CENTRE = "PERFORMING_ARTS_CENTRE";
export const MUSEUM = "MUSEUM";
export const CHURCH = "CHURCH";
export const CINEMA = "CINEMA";
export const OTHER = "OTHER";

export const ALLOWED_VALUES = [
  THEATRE,
  ART_GALLERY,
  CONCERT_HALL,
  EXHIBITION_HALL,
  PERFORMING_ARTS_CENTRE,
  MUSEUM,
  CHURCH,
  CINEMA,
  OTHER
];
