export const BOUNDED = "BOUNDED";
export const CONTINUOUS = "CONTINUOUS";
export const ONE_TIME = "ONE_TIME";

export const ALLOWED_VALUES = [BOUNDED, CONTINUOUS, ONE_TIME];
export const ALLOWED_PERFORMANCE_VALUES = ALLOWED_VALUES;
export const ALLOWED_COURSE_VALUES = [BOUNDED];
export const ALLOWED_EXHIBITION_VALUES = [BOUNDED, CONTINUOUS];
