scalar IsoShortDate

type HeroImage {
  name: String!
  dominantColor: String!
  label: String!
}

type HeroImagesResult {
  nodes: [HeroImage!]!
}

type NamedClosureList {
  type: String!
  dates: [IsoShortDate!]!
}

type NamesClosuresResult {
  lists: [NamedClosureList!]!
}

type Query {
  heroImages: HeroImagesResult
  namedClosures: NamesClosuresResult
}
